#!/usr/bin/env bash
# Transfer a file from client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 3 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	else
		echo scp -i "$4" "$1" "$3@$2"
		scp -i "$4" "$1" "$3@$2:$1"
fi
