#!/usr/bin/env bash
# Reconfigure Nginx

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
		root /usr/share/nginx/html;
        index index.html;
        server_name _;

        location / {
			try_files \$uri \$uri/ =404;
        }
}"

sudo mv --backup=t /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default.bak

echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
