#!/usr/bin/env bash
# Rewrite server blocks
sudo sed -ie 's/8080/80/g' /etc/nginx/sites-available/default
sudo sed -ie 's/server_name localhost/server_name _/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "" > /run/nginx.pid
