#!/usr/bin/env bash
# Displays `To infinity and beyond` indefinitely with a pause of 2 seconds
# and traps SIGTERM
trap "echo I am invisible!!!" SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
