#!/usr/bin/env bash
# Displays 1 to 20
# displays 4 and then `bad luck from China` on the 4th loop
# displays 9 and then `bad luck from Japan` on the 4th loop
# displays 17 and then `bad luck from Italy` on the 4th loop
i=1
while [ $i -le 20 ]; do
	echo "$i"
	case $i in
		4) echo "bad luck from China"
		;;
		9) echo "bad luck from Japan"
		;;
		17)	echo "bad luck from Italy"
		;;
	esac
	((i++))
done
