#!/usr/bin/env bash
# Configures an Ubuntu server with localhost resolving to 127.0.0.2 and facebook.com resolving to 8.8.8.8
cp /etc/hosts ~/hosts.bak
sed -i 's/127.*"$"127.0.0.2 localhost"\n"8.8.8.8 facebook.com/' ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
